### ISSUE TITLE
A few more needed libraries and a specific ArduinoJson and esp8266 core.

### ISSUE THREAD

**Issue by SputnikSeven** [xSnowHeadx/MinimalClock#1]
Hello, I'm not sure exactly the standard way of reporting issues, so sorry in advance. When compiling this I needed to also install WifiManager, ArduinoJson version 5, it would not compile using 6, and DoubleResetDetector. I also already had esp2866 core 3.02 installed and they seem to have changed the api around where it wouldn't compile. But reverting to 2.74 let it compile and it works beautifully.

**Comment by xSnowHeadx** [comment]
Thanks for the hints. The listed libraries are already specified in the README.md. But the hint regarding the arduino core 2.74 is important and will be added to the README.md.
Indeed using the sloeber-IDE I didn't make a core or library update for a longer time. I'll catch on making an update and try to get it run with the newest core.

**Comment by SputnikSeven** [comment]
NP and thanks again for making this!

**Comment by xSnowHeadx** [comment]
With the last commit now the core 3.0.2 can be used.
